#!/system/bin/sh

model=`getprop ro.product.model`

if [ "$model" = "LG-D410" ] || ["$model" = "LG-D405" ]  || ["$model" = "LG-D405n" ]; then
	mount -o remount,rw /system
	rm -rf /system/etc/permissions/android.hardware.nfc.xml
	rm -rf /system/etc/permissions/android.hardware.nfc.hce.xml
	mount -o remount,ro /system
fi
